{
 "title": "es日志",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "HOST",
    "label": "APP",
    "query": "{\"find\": \"terms\", \"field\": \"tag.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "nginx 500页面统计",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "200" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:nginx  AND(status:500)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "500页面详情",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "tag:nginx AND(status:500)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "nginx request  avg time TOP 20",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "request_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "tag:nginx",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "日志等级明细",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "debug",
     "type": "singlestat",
     "description": "debug",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "alias": "debug",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "loglevel:DEBUG AND tag:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "info",
     "type": "singlestat",
     "description": "info",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "alias": "info",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "loglevel:INFO AND tag:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "error",
     "type": "singlestat",
     "description": "error",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "alias": "error",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "loglevel:ERROR AND tag:$HOST",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "warn",
     "type": "singlestat",
     "description": "warn",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "alias": "warn",
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "loglevel:WARN AND tag:$HOST",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "线上ERROR错误日志统计",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "tag:java* AND(loglevel:ERROR)",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}