{
 "title": "JVM dashboard (for Prometheus Operator)",
 "description": "JMX exporter dashboard for metrics exported by Prometheus Operator",
 "tags": [ "JVM" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(jvm_info, namespace)"
   },
   {
    "name": "service",
    "query": "label_values(jvm_info{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(jvm_info{namespace=\"$namespace\", service=\"$service\"}, pod)"
   },
   {
    "name": "mempool",
    "label": "mem pool",
    "query": "label_values(jvm_memory_pool_bytes_max{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}, pool)"
   },
   {
    "name": "memarea",
    "label": "mem area",
    "query": "label_values(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}, area)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Memory area [$memarea]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "Upper limit"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Memory area [$memarea]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "Upper limit"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "repeat": "mempool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Max "
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Max "
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "loaded "
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Max "
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Max "
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "GC time increase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Memory pool [$mempool]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Max "
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",pool=\"$mempool\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  }
 ]
}