apiVersion: v1
data:
  alertmanager.yaml: Imdsb2JhbCI6IAogICJyZXNvbHZlX3RpbWVvdXQiOiAiNW0iCiAgInNtdHBfYXV0aF9wYXNzd29yZCI6ICJXeHk2NTQzMjEhQCMiCiAgInNtdHBfYXV0aF91c2VybmFtZSI6ICJnaXRsYWJAcWpkY2hpbmEuY29tIgogICJzbXRwX2Zyb20iOiAiZ2l0bGFiQHFqZGNoaW5hLmNvbSIKICAic210cF9yZXF1aXJlX3RscyI6IGZhbHNlCiAgInNtdHBfc21hcnRob3N0IjogInNtdHAubXhoaWNoaW5hLmNvbTo0NjUiCiJyZWNlaXZlcnMiOiAKLSAiZW1haWxfY29uZmlncyI6IAogIC0gInJlcXVpcmVfdGxzIjogZmFsc2UKICAgICJzZW5kX3Jlc29sdmVkIjogdHJ1ZQogICAgInRvIjogInlpbmdqaWFuamlhbkBxamRjaGluYS5jb20iCiAgIm5hbWUiOiAibWFpbCIKInJvdXRlIjogCiAgImdyb3VwX2J5IjogCiAgLSAiam9iIgogICJncm91cF9pbnRlcnZhbCI6ICI1bSIKICAiZ3JvdXBfd2FpdCI6ICIzMHMiCiAgInJlY2VpdmVyIjogIm1haWwiCiAgInJlcGVhdF9pbnRlcnZhbCI6ICIxMmgiCiAgInJvdXRlcyI6IAogIC0gIm1hdGNoIjogCiAgICAgICJhbGVydG5hbWUiOiAiRGVhZE1hbnNTd2l0Y2giCiAgICAicmVjZWl2ZXIiOiAibWFpbCI=
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
